### ISSUE TITLE
HTTP error 403

### ISSUE THREAD

**Issue by K4ktus123** [agnosto/fansly-recorder#7]
For starters, I would like to thank you for putting the time into writing this script - it's been quite useful. I stumbled upon one major issue though - I left it running for a few days and it managed to detect when the stream went live, but ffmpeg reported being denied access to the stream. Getting a fresh token got it working again. Is there anything that can be done to mitigate this?

**Comment by agnosto** [comment]
I'm not really sure, I personally never had that issue and I haven't actually used this in a while, but from what I remember from someone I know who helped when  testing, sometimes when they would log into the platform on desktop, they would have to change out the token following that, however logging in on phone never seemed to interfere, so that might be something to keep in mind.

 I'm not really sure what warrants the token needing to be refreshed as for both this and the [scraper](https://github.com/agnosto/fansly-scraper) I've gotten away with using the same token for quite a while and the only time I'd change them is if I was setting up a new environment and didn't back it up. Sorry I can't be of more help with this.

**Comment by K4ktus123** [comment]
Actually, I think this is exactly what I needed to know. Thank you!
